name: Pull request (preview) environment
on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Pull request number'
        required: true
        type: number
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Verify Pull Request Number
      uses: actions/github-script@v5
      id: verfiy_pr_number
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        result-encoding: string
        script: |
          const response = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{github.event.inputs.pull_request_number}}
          });

          if (response.data.number !== ${{github.event.inputs.pull_request_number}}){
          throw new Error('Pull request is not open or number is not valid')
          }else{
            console.log("PR ref: " + response.data.head.ref)
           return response.data.head.ref;
          }

    - uses: actions/checkout@v4
      with:
        ref: ${{steps.verfiy_pr_number.outputs.result}}
    - id: commit
      uses: prompt/actions-commit-hash@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: regoo707/sum-service:pull-request-${{github.event.inputs.pull_request_number}}-${{steps.commit.outputs.short}}
    

